channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - pip<=24.0
  - pip:
      - mlflow==2.19.0
      - cloudpickle==3.1.2
      - numpy==1.26.4
      - pandas==2.3.3
      - scikit-learn==1.5.0
      - dagshub
      - matplotlib
name: mlflow-env
